# Generated by Django 5.2.7 on 2025-12-30 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
